name: nanogpt
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1+3

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lnanogpt:
    path: rust_builder
  flutter_rust_bridge: 2.9.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - misc/icon.png
