name: nanogpt
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+4

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lnanogpt:
    path: rust_builder
  flutter_rust_bridge: 2.11.1

  logger: ^2.0.2+1
  go_router: ^14.8.1
  flutter_mobx: ^2.0.2
  mobx: ^2.2.1
  gap: ^3.0.1
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.1.2
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - misc/icon.png
